### ISSUE TITLE
api verbose and content

### ISSUE THREAD

**Issue by jeanfabre** [nicksergeant/snipt#147]
Hi,

 The content returned for a given snipt has a lot of information, and when searching with lots of results, this will affect bandwidth a lot.

 It would be nice to have options to cut down on the amount of info for a given snipt, typically, the objects:code and objects:stylized properties

 Regards,

 Jean

**Comment by nicksergeant** [comment]
Yeah, there's a lot of work that can be done around this, but for now I do have an `omit_code` querystring var that will at least strip out the raw code and simply give you the stylized text: https://snipt.net/api/public/snipt/?format=json&omit_code

**Comment by jeanfabre** [comment]
Hi,

 ok, thanks for the prompt reply, that's a first step indeed. Do you expect creating an omit_stylized or something or shall I close this comment?

 Bye and thanks for this great system you created!

 Jean

**Comment by nicksergeant** [comment]
I just deployed an option to also `omit_stylized`: https://github.com/nicksergeant/snipt/commit/9cef3b85e862e50a94db4afa189c78a7972fa7cd

**Comment by jeanfabre** [comment]
Thanks :)
