### ISSUE TITLE
custom properties for snipts

### ISSUE THREAD

**Issue by jeanfabre** [nicksergeant/snipt#148]
Hi,

First of all, diving more and more into your system, I think I found a real gem, thanks for your amazing work! 

I think a snipt with custom meta data would be truly unleashing potential, so that author can define custom properties. Right now, It's either we embed this meta data into the snipt itself or we use the description field, but I think it's not very clean. Typically, I see "tags" and "user" in the json object for a snipt. It would be great to have a "MetaData" or "Custom" additional/optional object, so that we can create our own context for snipt. 

I think it doesn't even need to be in the visual interface you present on the web application, but something that can be set with the api as a json, because this kind of feature typically make sense when integrating snipt as the source for content for applications.

Regards,

 Jean

**Comment by nicksergeant** [comment]
Great idea. I've added a `meta` field on all snipts, which can be access via the API: https://github.com/nicksergeant/snipt/commit/bc77c5c3e97a05af4673ce5230c3a2781fbb9d7b.
