### ISSUE TITLE
Missing Modified date of a snipt in the UI?

### ISSUE THREAD

**Issue by jeanfabre** [nicksergeant/snipt#149]
Hi,

 I can see a "modified" property in the json object of a snipt, but I can't see it mentionned in the front end UI. 

Is there a reason for this? I may miss the obvious.

Jean

**Comment by nicksergeant** [comment]
Hey Jean, no specific reason actually. I just added it in https://github.com/nicksergeant/snipt/commit/98a41a571987b946c25c9df86d5da31207a8a696.

**Comment by nicksergeant** [comment]
Actually I need to roll this back. Unfortunately the `views` count is tied directly to the resource, so whenever a new view is tacked on, the modified date changes. We need a larger architecture change here.
