### ISSUE TITLE
Link to raw url from the interface

### ISSUE THREAD

**Issue by jeanfabre** [nicksergeant/snipt#152]
Hi,

 I am currently improving the support for snipt sharing within my product, and introducing dependencies to other files. The problem if I can't really ask users to dig into the api to get the raw url, in that form:

https://snipt.net/raw/9e6d4b4eb1f4429130dab248f4be5186/

 So it would be great if the web interface could expose a "raw" button, ala Github for example. which I think would benefit also regular users to download the file easily with their browser.

Bye,

 Jean

**Comment by jeanfabre** [comment]
d'oh, did not pay attention, indeed the download button is there :)

**Comment by nicksergeant** [comment]
Ah! Glad you found it :)
