### ISSUE TITLE
api search missing result

### ISSUE THREAD

**Issue by jeanfabre** [nicksergeant/snipt#153]
Hi,

 There is this snipt: https://snipt.net/dudebxl/fighter3dcamera-1573b38d/

But if you search for "fighter" it doesn't return it, even tho it's in the class name. 

Is it because snipt searches whole words only?

Bye,

Jean

**Comment by nicksergeant** [comment]
Hmm, searching for `fighter` returns that snipt as the first result: https://snipt.net/search/?q=fighter

**Comment by jeanfabre** [comment]
?! Ok... that's odd, I waited two days before mentioning it here to double it was not some caching or some other potential issue, and yes it works now... Should have recorded a screencast :)

 Thanks anyway for your time.

Bye,

 Jean

**Comment by nicksergeant** [comment]
Computers are a strange species :)

**Comment by jeanfabre** [comment]
Human too I guess ...
