### ISSUE TITLE
Feature Request : Lexer for Unity based c#, Javascript, boo scripts?

### ISSUE THREAD

**Issue by jeanfabre** [nicksergeant/snipt#154]
Hi,

I see some variants on lexer languages, so maybe there is a place for a Unity variant of c# javascripts and boo in snip Lexer? 

https://unity3d.com/showcase

https://unity3d.com/learn/tutorials/modules/beginner/scripting/scripts-as-behaviour-components

https://unity3d.com/learn/tutorials/modules/beginner/scripting/c-sharp-vs-javascript-syntax

Basically, it's based on .NET20 with a very distinct api to work within Unity and create interactive 3d content, games obviously, but not just :)

I searched the snipts and found few examples, some of them in javascripts ( c# being the most used anyway)

https://snipt.net/search/?q=unity
https://snipt.net/fahied/using-accelerometer-in-unity-3d/

File extensions as .cs .js and .boo. I think mime types are regular.

Bye,

 Jean

**Comment by nicksergeant** [comment]
Hi Jean! We use Pygments, so if you write a new lexer for Pygments, it'll be added to Snipt in an update :)

Here's some info on writing new lexers: http://pygments.org/docs/lexerdevelopment/
