### ISSUE TITLE
Make error 255 (Ubuntu)

### ISSUE THREAD

**Issue by sogen** [nicksergeant/snipt#159]
followed instructions:
1.- Changed IP to own IP in Makefile, 
2.- Added Postgres DB settings in settings_local.py 
3.- Added id_rsa.pub key and it can connect to GitHub: `ssh -vT git@github.com`

But after running `make server`
I got this message:

```
Permission denied (publickey).
Makefile:108: recipe for target 'server' failed
make: *** [server] Error 255
```

more info:
make -v

```
GNU Make 4.1
Built for x86_64-pc-linux-gnu
```

**Comment by nicksergeant** [comment]
Hi, @sogen. Can you connect to your server with your pub key?

**Comment by sogen** [comment]
Yes, just tried it and it worked, added it with `cat publickey.pub authorized_keys`

Do any of the settings that need change use the long DNS name or the public IP?
i.e.: substitute the IP with the Public iP or use the long one: `ec2-XX-XXX-X-XX.us-west-2.compute.amazonaws.com`

Also, AWS EC2 has user "ubuntu" by default

**Comment by nicksergeant** [comment]
@sogen the Makefile is going to try to connect as the `root` user. If you're not logging in as the root user, change the username in a few places:

https://github.com/nicksergeant/snipt/blob/master/Makefile#L3

Also - sorry that this isn't more streamlined. I wrote the Makefile server bootstrapping stuff the first time I built out the new server, and you're the first person in several years to try using it :)

**Comment by nicksergeant** [comment]
So I'll be happy to help as best I can, but it might be a little rough going.

**Comment by nicksergeant** [comment]
So yeah I would first try replacing all instances of `96.126.110.160` with your IP or hostname (shouldn't matter), and all instances of `root` with the username you're connecting as... looks like maybe `ubuntu`.

**Comment by sogen** [comment]
k, will try, thx.
So, what's the easiest way to install it??

**Comment by nicksergeant** [comment]
@sogen the `make server` command is the easiest way to install Snipt on your own server. If you haven't deployed a Django app before, I would suggest also running through this: https://docs.djangoproject.com/en/1.10/topics/install/

That said, the Makefile and the SaltStack configuration install all of the dependencies needed for Snipt to run properly - PostgreSQL, ElasticSearch, etc.

Are you still having errors running the command?

**Comment by nicksergeant** [comment]
Also, you might have better luck deploying to Heroku:

https://github.com/nicksergeant/snipt#deploying-to-heroku

**Comment by sogen** [comment]
some advance, 
```

debconf: unable to initialize frontend: Dialog
debconf: (Dialog frontend will not work on a dumb terminal, an emacs shell buffer, or without a controlling terminal.)
debconf: falling back to frontend: Readline
update-rc.d: warning: start and stop actions are no longer supported; falling back to defaults

Makefile:108: recipe for target 'server' failed
make: *** [server] Error 100
```
will ty the docker route and let you know, thanks

**Comment by nicksergeant** [comment]
Hrm. I have no idea what that error might be.

Another option would be to use Dokku on your VPS: https://github.com/dokku/dokku, and then install via the Heroku instructions in the README.

**Comment by nicksergeant** [comment]
Closing this ticket, as moving forward I won't be supporting the Salt Stack / VM route for running Snipt. You can follow this branch, where I'm focused on building a one-click install for Heroku: https://github.com/nicksergeant/snipt/tree/heroku

**Comment by sogen** [comment]
thumbs up :)
