### ISSUE TITLE
Error in deploying the app to Heroku - could not determine PostgreSQL version from '10.1'

### ISSUE THREAD

**Issue by gal20040** [nicksergeant/snipt#166]
Hey Nick!

I'm trying to deploy the app to Heroku with the button 'Deploy to Heroku' but I'm getting error "could not determine PostgreSQL version from '10.1'" while collecting psycopg2==2.6.2:
https://pastebin.com/F9gGcbr0

What can I do with it?

**Comment by nicksergeant** [comment]
@gal20040 thanks for the report! Fixed in https://github.com/nicksergeant/snipt/commit/d013359af5f7139da0caf12d1a0d838fd65f69eb.
