### ISSUE TITLE
Require fill in tags

### ISSUE THREAD

**Issue by gal20040** [nicksergeant/snipt#167]
Hi!

Can you add ability to require the adding of tags (at least one)? Without tags just added snippet will be lost after adding some new snippets.
Adding attribute 'required' to textarea doesn't work.

Thank you for the app!

-- 
Artem

**Comment by nicksergeant** [comment]
Hi @gal20040! I'm not sure that makes sense for everyone, though, as I often would save snipts without a tag. Curious what you mean by them getting "lost" though. Are you seeing some snipts disappear from the paginated results or search results?

**Comment by gal20040** [comment]
>Are you seeing some snipts disappear from the paginated results or search results?
No. I mean that I can not find them among others. It is "my problem" with some other snippet tool.

Can you tell me how can I set the tags field mandatory for my instance?

**Comment by nicksergeant** [comment]
@gal20040 there is currently no functionality that would allow you to require tags for snipts in your instance. You could add this functionality restricting the save of a new snipt here: https://github.com/nicksergeant/snipt/blob/master/media/js/src/modules/snipt.js#L490

**Comment by gal20040** [comment]
Thank you, Nick!

**Comment by nicksergeant** [comment]
@gal20040 absolutely! Let me know how it works out :)
