### ISSUE TITLE
Account ID or alias

### ISSUE THREAD

**Issue by Anondobangla** [nicksergeant/snipt#170]

**Comment by nicksergeant** [comment]
@Anondobangla could you clarify what you're looking for with this issue? Thanks!

**Comment by Anondobangla** [comment]
Who is my administrator? https://aws.amazon.com/console/faqs/ is site email abmfaridahmed121@gmail.com

**Comment by nicksergeant** [comment]
@Anondobangla I’m not sure what you’re referring to. This is the GitHub sourcecode repository for Snipt, a code snippet storage app.
