### ISSUE TITLE
Incorrect link when clicking on a snipt.

### ISSUE THREAD

**Issue by allyouaskfor** [nicksergeant/snipt#174]
I've deployed through Heroku and successfully created a user account and added a 'snipt' to test it out. After saving, I return to the Snipt homepage by clicking the logo at the top-left and I can see that it has been saved but when I click on the snipt I created, it attempts to take me to `<user>.snipt.net/<snipt-name>`. I do not have a URL pointing towards it or any CNAME set up for it.

**Comment by nicksergeant** [comment]
@allyouaskfor did you by chance mark the snipt as "blog post"? If so, the primary link to the snipts will attempt to link to our old blog integration.

**Comment by allyouaskfor** [comment]
Apparently I did. Switching that off resolved the issue. Thank you.
