### ISSUE TITLE
Build commenting system to replace Disqus.

### ISSUE THREAD

**Issue by nicksergeant** [nicksergeant/snipt#53]
Disqus is forcing their new "2012" platform on all users. This platform showcases URLs from throughout the site in the "Community" tab. Unfortunately Disqus doesn't believe in private comments on a site, so this means that if comments on a private Snipt make a URL "trending", that private snipt would show up in the public "Community" tab. This is obviously a security concern for private snipts.

**Comment by Dudintv** [comment]
I store my history of changes in comments! How can I restore my comments in private Snipt?

**Comment by nicksergeant** [comment]
Hi @dudintv, can you email me at support@snipt.net with your account information?
